apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: @@namespace@@
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: external-dns-pdns
stringData:
  api-key: @@pdns-api-key@@
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      # TODO add reservations and limits.
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:v0.7.6
          args:
            - --source=service
            - --source=ingress
            - --provider=pdns
            - --pdns-server=@@pdns-server@@
            - --txt-owner-id=@@txt-owner-id@@
            - --domain-filter=@@domain-filter@@
            - --log-level=debug
            - --interval=30s
          env:
            - name: EXTERNAL_DNS_PDNS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-dns-pdns
                  key: api-key
